# Generated by Django 6.0 on 2025-12-06 07:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the district', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the election (e.g., '2025 Gram Panchayat Elections')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the election')),
                ('start_time', models.DateTimeField(help_text='When voting starts')),
                ('end_time', models.DateTimeField(help_text='When voting ends')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this election is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(help_text='10-digit mobile number (used for voter identification)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
            },
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the mandal', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(help_text='District this mandal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mandals', to='elections.district')),
            ],
            options={
                'verbose_name': 'Mandal',
                'verbose_name_plural': 'Mandals',
                'ordering': ['district__name', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the village/gram panchayat', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandal', models.ForeignKey(help_text='Mandal this village belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='elections.mandal')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['mandal__district__name', 'mandal__name', 'name'],
                'unique_together': {('mandal', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Ward number within the village')),
                ('name', models.CharField(blank=True, help_text='Optional descriptive name for the ward', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(help_text='Village this ward belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='elections.village')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['village__name', 'number'],
                'unique_together': {('village', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the candidate', max_length=200)),
                ('position_type', models.CharField(choices=[('SARPANCH', 'Sarpanch'), ('WARD_MEMBER', 'Ward Member')], help_text='Type of position: Sarpanch or Ward Member', max_length=20)),
                ('party_name', models.CharField(blank=True, help_text='Political party or affiliation (optional)', max_length=100)),
                ('symbol', models.CharField(blank=True, help_text='Election symbol (optional)', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Candidate photo (optional)', null=True, upload_to='candidates/')),
                ('bio', models.TextField(blank=True, help_text='Brief biography of the candidate (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(help_text='Election this candidate is participating in', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('village', models.ForeignKey(help_text='Village for this candidacy', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.village')),
                ('ward', models.ForeignKey(blank=True, help_text='Ward for Ward Member candidates (NULL for Sarpanch)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.ward')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['election', 'village', 'position_type', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the voter (for audit)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent (for audit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(help_text='Election for this vote', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
                ('sarpanch_candidate', models.ForeignKey(blank=True, help_text='Sarpanch candidate voted for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sarpanch_votes', to='elections.candidate')),
                ('village', models.ForeignKey(help_text='Village where the vote was cast', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.village')),
                ('ward_member_candidate', models.ForeignKey(blank=True, help_text='Ward Member candidate voted for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ward_member_votes', to='elections.candidate')),
                ('voter', models.ForeignKey(help_text='Voter who cast this vote', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.voter')),
                ('ward', models.ForeignKey(blank=True, help_text='Ward for the Ward Member vote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='elections.ward')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-created_at'],
                'unique_together': {('election', 'voter', 'village')},
            },
        ),
    ]
