# Generated by Django 5.2.9 on 2025-12-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Local Elections', help_text='Main site name displayed in header', max_length=200)),
                ('site_tagline', models.CharField(default='Voting System', help_text='Tagline displayed below site name', max_length=300)),
                ('footer_text', models.CharField(blank=True, default='Gram Panchayat Elections Management', help_text='Text displayed in footer', max_length=500)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email (optional)', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=20)),
                ('about_text', models.TextField(blank=True, help_text='About section text for landing page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
