# Generated by Django 5.2.9 on 2025-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='promises_csv',
            field=models.TextField(blank=True, help_text='Example: Free drinking water, Road repairs, Street lights, Women empowerment programs', verbose_name='Welfare activities / promises (comma-separated)'),
        ),
    ]
