# Generated by Django 5.2.9 on 2025-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_candidate_promises_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='family_vote_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of family members voting together (default: 1)'),
        ),
        migrations.AddField(
            model_name='voter',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the voter', max_length=200),
        ),
    ]
