# Generated by Django 5.2.9 on 2025-12-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_vote_family_vote_count_voter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this candidate from voting (e.g., if withdrawn)', verbose_name='Active'),
        ),
    ]
