# Generated by Django 5.2.9 on 2025-12-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_candidate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='symbol_url',
            field=models.URLField(blank=True, help_text='Direct URL to the election symbol image (optional)', max_length=500),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.CharField(blank=True, help_text="Election symbol name (optional, e.g., 'Bicycle', 'Fan')", max_length=100),
        ),
    ]
