# Generated by Django 5.2.9 on 2025-12-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_candidate_symbol_url_alter_candidate_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this village from voting (e.g., if not participating in election)', verbose_name='Active'),
        ),
    ]
